name: playlist_mobile
description: "Download e Reprodução de Playlist MP3 (Avaliação em grupo)"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  http: ^1.2.2
  dio: ^5.7.0
  path_provider: ^2.1.4
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.10
  audio_service: ^0.18.12

dependency_overrides:
  audio_service: ^0.18.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
