name: playlist_mobile
description: "Download e Reprodução de Playlist MP3 (Avaliação em grupo)"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.39
  path_provider: ^2.1.3
  dio: ^5.4.3+1
  http: ^1.5.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
